#pragma once
#include <stdio.h>
#include "struct.h"
void color1();//背景颜色
void changecolor1();//修改背景颜色
void registers();//登录,验证密码
void showroomtype();//显示房间类型
void inquirevacant();//查询选择的房间是否有空房，并输出查询结果。
void interface();//显示界面
Room* readroom();//从文件里面读出来room放到链表里面
void saveroom();//保存文件信息
void emptyroom();//清空一个房间
void inputroom();//填写一个房间
Order* exploitorderhead();//开辟一个订单头
void chooseroomtype();//选择房间类型
int judgeid();//判断身份证号码是否符合要求
int judgephone();//判断电话号是否符合要求11位全数字
void openroom();//开房
void saveorder();//保存订单
Order* readorder();//读取订单
int Check_date1();//检验日期是否合法
int Check_date2();//检验日期是否合法
void deletedisabledorder();//删除失效订单
int Check_date3();//检验日期是否合法
void checkchar();//将字符串后面的\n去掉
void checkchar1();//将字符串后面加上\n
void changeorder();//修改订单
void deleteorder();//删除订单
void changeKEY();//修改密码
void search2();//查询订单
void search1();//查询房间
void statistics();//统计订单
int time_1();// 检查订单时间是否大于输入时间
int Check_date4();
void read_();//读取数据
void backups();//备份
int FindSubstring();//查询字串
